pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    service_name: project-assessment-site
    service_type: REST
spec:
  containers:
  - name: dvd
    image: docker:latest
    command: 
    - cat
    tty: true
    volumeMounts: 
    - mountPath: /var/run/docker.sock
      name: docker-sock
  - name: kubectl
    image: bryandollery/terraform-packer-aws-alpine
    command:
    - cat
    tty: true
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock  
      type: Socket
"""
    }
  }
  environment {
    CREDS = credentials('fatima_docker_creds')
    DOCKER_NAMESPACE = 'fatimahobaidan'
    SERVICE_NAME = 'project-assessment-site'
    TOKEN=credentials('2b28865e-3dc7-406f-abd3-3e17aba46488')
  }
  stages {
      stage("Build") {
          steps {
              container('dvd') {
                  sh '''
                      cd $SERVICE_NAME
                      docker build --tag $DOCKER_NAMESPACE/$SERVICE_NAME .
                  '''
              }
          }
      }
      stage("Release") {
          steps {
              container('dvd') {
                  sh '''
                      docker login -p $CREDS_PSW -u $CREDS_USR
                      docker push $DOCKER_NAMESPACE/$SERVICE_NAME
                  '''
              }
          }
      }
      stage("Deploy") {
          steps {
              container('kubectl') {
                  sh '''
                      cd $SERVICE_NAME
                      kubectl --token=$TOKEN -n test get all
                      kubectl --token=$TOKEN -n test apply -f deploy.yaml -f service.yaml
                      kubectl --token=$TOKEN -n test get all
                  '''
              }
          }
      }
  }
}
